AY2425S1-CS2103T-T11-3/tp

docs/_markbind/layouts/default.md
docs/site.json

Merged markbind branch and followed the tutorial.

Add markbind support

---

docs/_markbind/layouts/default.md
docs/site.json

Reverts AY2425S1-CS2103T-T11-3/tp#9

Revert "Add markbind support"

---

docs/AboutUs.md

Added my role and responisbilities in the project.

Edit about us page

---

docs/AboutUs.md

Updated AboutUS page to include personal profile.

Update AboutUS page

---

docs/DeveloperGuide.md

Updated the Non functional requirement using the
template provided in the Developer Guide for AB3
and included the constraints provided.

Edit NFR in the Developer Guide

---

README.md
docs/AboutUs.md
docs/DevOps.md
docs/DeveloperGuide.md
docs/Documentation.md
docs/Logging.md
docs/SettingUp.md
docs/Testing.md
docs/UserGuide.md
docs/index.md

README badges point to our repo. Fixed formatting
bug of markbind not applying.

Update README and formatting bug fix

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

Added view command. 
Allows the user to view the contact of a person using a keyword.

Add view command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

when filteredList is empty,
"There is nothing to delete" will be thrown
when index is out of bound, "The person index provided is invalid,
please enter an index that is between 1 and <list_size>.”
tests related was updated too

Match delete exception cases to feature list

---

src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/person/TagContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/TagContainsKeywordPredicateTest.java

No tests, just vibes
Filter command by `filter x y z` and will return all the people with tags x || y || z.

Filter command

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/test/java/seedu/address/logic/commands/AddCommandTest.java
src/test/java/seedu/address/model/person/PersonTest.java

allowed new contacts with same number or email
it is impossible for different people to have the same number or email
updated to reject new contacts with same number or email

update add command feature

---

src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java

Extra spaces between first / middle / last names will eliminated.

Update view command to accept new values

---

src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/TagCommandParser.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/TagCommandTest.java
src/test/java/seedu/address/logic/commands/TagPersonDescriptorTest.java
src/test/java/seedu/address/testutil/TagPersonDescriptorBuilder.java

Add Tag Command and some data validation, including non-empty tags like "t/" and duplicate tags.

Add TagCommand

---

src/main/java/seedu/address/model/wedding/ContactMap.java
src/main/java/seedu/address/model/wedding/Date.java
src/main/java/seedu/address/model/wedding/Role.java
src/main/java/seedu/address/model/wedding/Wedding.java

- Updated equals methods
- Using LocalDate instead

Fix small bugs in wedding package

---

src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/wedding/ContactSet.java
src/main/java/seedu/address/model/wedding/Wedding.java

ContactMap changed to ContactSet
Wedding class adapted to ContactSet
Person class no longer requires Tag to not be null

Modify ContactSet, Wedding, Person class

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddwCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/AddwCommandParser.java
src/main/java/seedu/address/logic/parser/CliSyntax.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/person/Person.java

Current issues
- Wedding not added to storage (guanyi doing)
- Command prompt needs to be modified to fit new format (guanyi help!)
- ParseClient in ParserUtil needs modification to fit parsing by name or index (shernice help!)
Other Notes
- Tests fail due to previous changes to Wedding and Person classes

Add addw command

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/EditwCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/EditwCommandParser.java

GUI issues persist
can edit like this
`editw [index] n/[new name] v/[new venue] d/[new date]` 
idk if it actually works fully bopes.

Add edit weddings

---

src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java

Made tag optional to include in add command

Fix tag property in add command

---

src/main/java/seedu/address/logic/commands/TagCommand.java
src/main/java/seedu/address/model/wedding/Client.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java
src/test/java/seedu/address/logic/commands/TagCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/AddressBookTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/TagContainsKeywordPredicateTest.java
src/test/java/seedu/address/model/person/UniquePersonListTest.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/TagPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalPersons.java
src/test/java/seedu/address/testutil/WeddingUtil.java

Edit person builder

---

src/main/java/seedu/address/model/util/SampleDataUtil.java
src/test/data/JsonAddressBookStorageTest/invalidAndValidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidAndValidWeddingAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidPersonAddressBook.json
src/test/data/JsonAddressBookStorageTest/invalidWeddingAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicatePersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/duplicateWeddingAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidPersonAddressBook.json
src/test/data/JsonSerializableAddressBookTest/invalidWeddingAddressBook.json

Modify and add addressBook json files for test
Edit SampleDataUtil

Modify json files and sample data util

---

src/main/java/seedu/address/logic/commands/RoleCommand.java
src/main/java/seedu/address/logic/parser/RoleCommandParser.java
src/test/java/seedu/address/logic/commands/RoleCommandTest.java

Can now assign by index or name with the given format:
- assign NAME r/ROLE
- assign INDEX r/ROLE
If there are multiple contacts with the same name keyword, user will be prompted to assign by index.
This is similar to the edit feature.

Refine RoleCommand 

---

src/main/java/seedu/address/logic/commands/RoleCommand.java
src/main/java/seedu/address/logic/parser/RoleCommandParser.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/commands/EditPersonDescriptorTest.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/commands/RoleCommandTest.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/logic/parser/EditCommandParserTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/PersonTest.java
src/test/java/seedu/address/model/person/RoleContainsKeywordPredicateTest.java
src/test/java/seedu/address/storage/JsonAdaptedPersonTest.java
src/test/java/seedu/address/storage/JsonAdaptedWeddingTest.java
src/test/java/seedu/address/storage/JsonSerializableAddressBookTest.java
src/test/java/seedu/address/testutil/EditPersonDescriptorBuilder.java
src/test/java/seedu/address/testutil/EditWeddingDescriptorBuilder.java
src/test/java/seedu/address/testutil/PersonBuilder.java
src/test/java/seedu/address/testutil/PersonUtil.java
src/test/java/seedu/address/testutil/PersonWithRoleDescriptorBuilder.java
src/test/java/seedu/address/testutil/TypicalWeddings.java
src/test/java/seedu/address/ui/suggestion/FormatSuggestionTest.java
src/test/java/seedu/address/ui/suggestion/SuggestionsTest.java

Tweak imports

---

src/main/java/seedu/address/commons/core/index/Index.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/model/wedding/Client.java
src/test/java/seedu/address/logic/LogicManagerTest.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

- Debugged Validation Regex for Index in Client
- Debugged ParserUtil
- Included hashcode method in Index for HashSet::equals to work

Add LogicManagerTest and ParserUtil Test

---

src/main/java/seedu/address/model/wedding/UniqueWeddingList.java
src/main/java/seedu/address/model/wedding/exceptions/DuplicateWeddingException.java
src/main/java/seedu/address/model/wedding/exceptions/WeddingNotFoundException.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java
src/test/java/seedu/address/model/person/NameMatchesKeywordPredicateTest.java
src/test/java/seedu/address/model/person/UniquePersonListTest.java
src/test/java/seedu/address/model/wedding/ClientTest.java
src/test/java/seedu/address/model/wedding/NameMatchesWeddingPredicateTest.java
src/test/java/seedu/address/model/wedding/UniqueWeddingListTest.java
src/test/java/seedu/address/testutil/TypicalWeddings.java

Added tests for ClientTest.java, NameMatchesWeddingPredicateTest.java, UniqueWeddingListTest.java
Added new exceptions for Wedding class: DuplicateWeddingException.java and WeddingNotFoundException.java
Note: One of the tests in UniqueWeddingListTest.java fails, will fix it soon!

Create wedding tests

---

src/main/java/seedu/address/logic/commands/AddwCommand.java
src/test/java/seedu/address/logic/commands/AddwCommandTest.java
src/test/java/seedu/address/logic/parser/AddwCommandParserTest.java

- Not entirely covered by 85% of methods covered
- One method is commented out, will try to figure it out asap
- Fix AddwCommandParserTest

Add AddwCommandTest

---

src/main/java/seedu/address/logic/commands/FilterCommand.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
src/test/java/seedu/address/logic/commands/FilterCommandTest.java
src/test/java/seedu/address/logic/parser/FilterCommandParserTest.java
src/test/java/seedu/address/model/person/AddressContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/EmailContainsKeywordsPredicateTest.java
src/test/java/seedu/address/model/person/PhoneContainsKeywordsPredicateTest.java

- Added more tests to predicates
- Filtering works with OR now
- Suggestions still needs an update

Fix filter

---

docs/DeveloperGuide.md
docs/UserGuide.md

- Added section for filtering.

Edit UG DG for Filter

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddwCommand.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/wedding/Wedding.java
src/test/java/seedu/address/logic/commands/AddwCommandTest.java

* Debug Addw Successful Message
* Debug Addw Dulplicate Client Message
* Modify Name REGEX to cap at 7- chars
* Add Test Case to accomodate changed addw success message

Debug Addw Command

---

src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/FilterCommand.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java

- Throws error when client of a wedding is attempted to be deleted

Twek delete command

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/commands/AddCommand.java
src/main/java/seedu/address/logic/commands/AddwCommand.java
src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/commands/ViewwCommand.java
src/main/java/seedu/address/ui/suggestion/Commands.java

More bug fixes

---

src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/DeleteCommand.java
src/main/java/seedu/address/logic/commands/DeletewCommand.java
src/main/java/seedu/address/logic/parser/AddressBookParser.java
src/main/java/seedu/address/logic/parser/DeletewCommandParser.java
src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/ui/suggestion/Commands.java
src/test/java/seedu/address/logic/commands/CommandTestUtil.java
src/test/java/seedu/address/logic/commands/DeleteCommandTest.java
src/test/java/seedu/address/logic/commands/DeletewCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/DeletewCommandParserTest.java
src/test/java/seedu/address/model/person/PersonTest.java

Added deletew command.
When wedding is deleted:
- the ownWedding of client will be reset
- people who have wedding as wedding job will have it removed from their list

Deletew command

---

src/main/java/seedu/address/logic/commands/AssignCommand.java
src/main/java/seedu/address/logic/commands/ViewCommand.java
src/main/java/seedu/address/logic/commands/ViewwCommand.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/wedding/PersonHasWeddingPredicate.java
src/main/java/seedu/address/ui/WeddingCard.java
src/main/java/seedu/address/ui/suggestion/Commands.java
src/test/java/seedu/address/logic/commands/ViewCommandTest.java
src/test/java/seedu/address/logic/commands/ViewwCommandTest.java
src/test/java/seedu/address/logic/parser/AddressBookParserTest.java
src/test/java/seedu/address/logic/parser/ViewCommandParserTest.java
src/test/java/seedu/address/model/wedding/PersonHasWeddingPredicateTest.java
src/test/java/seedu/address/testutil/TypicalPersons.java

Bugs fixed:
- #149 
- #162 
For Issue #162:
- for vieww NAME, when there are duplicates, the person list will be refreshed to show all persons. Only when there are no duplicates or index (i.e. one unique wedding to view), will the person list will filtered to give persons involved.
- for assign command, made it such that after assign finish successfully (no duplicates, no exceptions), person list refreshed to all persons.

More bug fixes again

---

src/main/java/seedu/address/storage/JsonAdaptedWedding.java
src/test/java/seedu/address/storage/JsonAdaptedWeddingTest.java

Changed saving date and venue
Changed reading of date and venue from address book

Debug addressbookjson loading

---

docs/DeveloperGuide.md

did this for view, delete, vieww and deletew

Add manual testing cases for DG

---

src/main/java/seedu/address/ui/CommandBox.java
src/main/resources/view/DarkTheme.css

the text field will now overlay the suggestion field, if look carefully can see the suggestion behind the text field, 
when an error occur, the suggestion will be cleared, will reappear if user continue typing.

fix suggestion indent issue

---

src/main/java/seedu/address/logic/commands/EditCommand.java
src/test/java/seedu/address/logic/commands/EditCommandTest.java

Edit command didn't allow for editing of people without weddings, should be fixed now.

Fix edit command bug

---

docs/UserGuide.md
docs/diagrams/UiClassDiagram.puml

Add line breaks for images in UG
Update ui diagram for DG

Add line breaks for images in UG

---

docs/UserGuide.md
src/main/java/seedu/address/logic/commands/EditCommand.java
src/main/resources/view/MainWindow.fxml

Issues addressed:
- #225: Checked with the prof. This is allowed!
- #246: Fixed the error message, which was initially wrong.
- #221: Added a link to validation rules under editw command.
- #241 
- #228 
- #243 
- #285 
- #275 
- #245

PE-D fixes

---

docs/DeveloperGuide.md
src/main/resources/view/MainWindow.fxml

extending white space fix

---

src/main/java/seedu/address/model/wedding/Date.java

Date parsing modification

---

docs/UserGuide.md

Made the introduction more personalised (?) for Bridal Boss

Make changes in introduction

---

src/main/java/seedu/address/logic/Messages.java
src/main/java/seedu/address/logic/parser/AddCommandParser.java
src/main/java/seedu/address/logic/parser/AddwCommandParser.java
src/main/java/seedu/address/logic/parser/AssignCommandParser.java
src/main/java/seedu/address/logic/parser/DeleteCommandParser.java
src/main/java/seedu/address/logic/parser/DeletewCommandParser.java
src/main/java/seedu/address/logic/parser/EditCommandParser.java
src/main/java/seedu/address/logic/parser/EditwCommandParser.java
src/main/java/seedu/address/logic/parser/FilterCommandParser.java
src/main/java/seedu/address/logic/parser/FindCommandParser.java
src/main/java/seedu/address/logic/parser/ParserUtil.java
src/main/java/seedu/address/logic/parser/ViewCommandParser.java
src/main/java/seedu/address/logic/parser/ViewwCommandParser.java
src/test/java/seedu/address/logic/parser/ParserUtilTest.java

Biggest change was that I abstracted all the `isNumeric` method into ParserUtil to reduce code duplication.

Check code quality for parser

---

src/main/java/seedu/address/model/AddressBook.java
src/main/java/seedu/address/model/Model.java
src/main/java/seedu/address/model/ModelManager.java
src/main/java/seedu/address/model/person/AddressContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/ClientMatchesWeddingPredicate.java
src/main/java/seedu/address/model/person/Email.java
src/main/java/seedu/address/model/person/EmailContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/Name.java
src/main/java/seedu/address/model/person/NameContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/NameMatchesKeywordPredicate.java
src/main/java/seedu/address/model/person/Person.java
src/main/java/seedu/address/model/person/PersonMatchesWeddingPredicate.java
src/main/java/seedu/address/model/person/Phone.java
src/main/java/seedu/address/model/person/PhoneContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/RoleContainsKeywordsPredicate.java
src/main/java/seedu/address/model/person/UniquePersonList.java
src/main/java/seedu/address/model/role/Role.java
src/main/java/seedu/address/model/util/SampleDataUtil.java
src/main/java/seedu/address/model/wedding/Client.java
src/main/java/seedu/address/model/wedding/Date.java
src/main/java/seedu/address/model/wedding/NameMatchesWeddingPredicate.java
src/main/java/seedu/address/model/wedding/UniqueWeddingList.java
src/main/java/seedu/address/model/wedding/Venue.java
src/main/java/seedu/address/model/wedding/Wedding.java
src/main/java/seedu/address/model/wedding/WeddingMatchesClientPredicate.java
src/main/java/seedu/address/model/wedding/exceptions/DuplicateWeddingException.java
src/test/java/seedu/address/logic/parser/AddCommandParserTest.java
src/test/java/seedu/address/model/role/RoleTest.java
src/test/java/seedu/address/model/wedding/ClientTest.java

- Add javadocs
- Fix person equals, fix test case

code clean model
